workflows:
    gradle-build:
      name: Gradle
      instance_type: mac_mini
      environment:
        java: 11
        vars:
          AWS_ACCESS_KEY_ID: Encrypted(Z0FBQUFBQmd3T25adXpUNjFEdTB4cUlsdFJPLVFPZU5VQXVLZHprS01HYlZCcy1ONS0wSUNOLVVkSnR1TXY2T29ub0JKbldyN0o3VU03bFhIbWkxbU1fSU0yc0hVeG5QNGhFbUx0ZnVsUDhadWUtcEFRejFtdGM9)
          AWS_REGION: eu-west-1
          AWS_SECRET_ACCESS_KEY: Encrypted(Z0FBQUFBQmd3T29MSWpJeHFvMXkwYlRncnYyM25rMkU0UWRDZTJkN3F4czcwSG9EbEN5VlVTaVFxTVU2ZGgxUjQzSTdzN1lOb3dkelNEQjFkSjg4OTROS3k0blA1akV5a0tKWjdPOS01TDRuVTI3NGoyOHF3Qkh5a2NYeGE5VU9OelN1NnZXT0Y0MEQ=)
      scripts:
        - name: Run unit tests
          script: ./gradlew KMPExampleModule:check
        - name: Create swift package
          script: ./gradlew KMPExampleModule:createSwiftPackage
        - name: Upload binary to s3
          script: |
            sudo pip3 install awscli --upgrade
            ls
            aws s3 sync ./KMPExampleModule/swiftpackage/ s3://unidays-app-dependencies/ios/KMPExampleModule --exclude '*' --include '*.zip' --exclude '*/*'
      artifacts:
        - KMPExampleModule/swiftpackage/*.zip
    test-pull-request:
      name: Test Pull Request
      instance_type: mac_mini
      triggering:
        events:
          - pull_request
        branch_patterns:
          - pattern: '*'
            include: true
            source: true
      scripts:
        - name: Install Java 15.0.2
          script: |
            curl -O https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_osx-x64_bin.tar.gz
            sudo rm -R /Library/Java/JavaVirtualMachines/*
            sudo mv openjdk-15.0.2_osx-x64_bin.tar.gz /Library/Java/JavaVirtualMachines/
            cd /Library/Java/JavaVirtualMachines
            sudo tar -xzf openjdk-15.0.2_osx-x64_bin.tar.gz
            sudo rm openjdk-15.0.2_osx-x64_bin.tar.gz
            /usr/libexec/java_home -v15
            sed -i.old -E '/JAVA_HOME=*/d' ~/.bash_profile
            export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home
            echo "JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home" >> ~/.bash_profile
            source ~/.bash_profile
        - name: Run Unit Tests and Coverage
          script: |
            export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home
            echo $JAVA_HOME
            ./gradlew -Dorg.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home build KMPExampleModule:testCoverage
      artifacts:
        - KMPExampleModule/build/jacocoHtml/com.example.kmpexamplemodule/index.html

