workflows:
    gradle-build:
      name: Gradle
      instance_type: mac_mini
      cache:
        cache_paths:
          - ~/.gradle/caches
      environment:
        vars:
          AWS_ACCESS_KEY_ID: Encrypted(Z0FBQUFBQmd3T25adXpUNjFEdTB4cUlsdFJPLVFPZU5VQXVLZHprS01HYlZCcy1ONS0wSUNOLVVkSnR1TXY2T29ub0JKbldyN0o3VU03bFhIbWkxbU1fSU0yc0hVeG5QNGhFbUx0ZnVsUDhadWUtcEFRejFtdGM9)
          AWS_REGION: eu-west-1
          AWS_SECRET_ACCESS_KEY: Encrypted(Z0FBQUFBQmd3T29MSWpJeHFvMXkwYlRncnYyM25rMkU0UWRDZTJkN3F4czcwSG9EbEN5VlVTaVFxTVU2ZGgxUjQzSTdzN1lOb3dkelNEQjFkSjg4OTROS3k0blA1akV5a0tKWjdPOS01TDRuVTI3NGoyOHF3Qkh5a2NYeGE5VU9OelN1NnZXT0Y0MEQ=)
          JAVA_LOCATION: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home
      scripts:
        - &install_java_15
          name: Install Java 15.0.2
          script: ./codeMagicScripts/installJava15.sh
        - &run_unit_tests
          name: Run Unit Tests
          script: |
            source ~/.bash_profile
            export JAVA_HOME=$JAVA_LOCATION
            ./gradlew -Dorg.gradle.java.home=$JAVA_LOCATION build KMPExampleModule:test
        - &verify_tests_coverage
          name: Verify Tests Coverage
          script: |
            source ~/.bash_profile
            export JAVA_HOME=$JAVA_LOCATION
            ./gradlew -Dorg.gradle.java.home=$JAVA_LOCATION build KMPExampleModule:verifyCoverage
        - name: Create Swift Package
          script: |
            source ~/.bash_profile
            export JAVA_HOME=$JAVA_LOCATION
            ./gradlew -Dorg.gradle.java.home=$JAVA_LOCATION KMPExampleModule:createSwiftPackage
        - name: Upload Binary to S3
          script: |
            sudo pip3 install awscli --upgrade
            ls
            aws s3 sync ./KMPExampleModule/swiftpackage/ s3://unidays-app-dependencies/ios/KMPExampleModule --exclude '*' --include '*.zip' --exclude '*/*'
      artifacts:
        - KMPExampleModule/swiftpackage/*.zip
    test-pull-request:
      name: Test Pull Request
      instance_type: mac_mini
      environment:
        vars:
          JAVA_LOCATION: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home
      cache:
        cache_paths:
          - ~/.gradle/caches
      triggering:
        events:
          - pull_request
        branch_patterns:
          - pattern: '*'
            include: true
            source: true
      scripts:
        - *install_java_15
        - *run_unit_tests
        - *verify_tests_coverage
      artifacts:
        - KMPExampleModule/build/jacocoHtml/

